### ISSUE TITLE
Browser optimizing

### ISSUE THREAD

**Issue by Jesperkm** [Morning-Train/Mail-notifications-for-Trello#4]
- Border radius on close button doesn't look well on safari

- Edit button not working on Firefox

- Select field style not working properly on crossbrowser

--- RESOLVED

**Comment by Jesperkm** [comment]
Select field issue fixed

**Comment by Rubatharisan** [comment]
Well done Jesper :D

2015-03-13 9:56 GMT+01:00 Jesper Martinussen <notifications@github.com>:

> Select field issue fixed
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/Morning-Train/Trello-Train/issues/4#issuecomment-78874658>
> .
>



-- 

Med venlig hilsen,
*Rubatharisan Thirumathyam*

**Comment by Jesperkm** [comment]
Border-radius bugg fixed

**Comment by Jesperkm** [comment]
Edit button bugg fixed
